name: Run tests

on:
  push:
    branches:
      - main

jobs:
  fetch-core-libs:
    runs-on: ubuntu-22.04
    env:
      CORE_LIB_REPO: tomwyr/godot-node-tree-core
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Resolve core lib version
        id: resolve-version
        run: scripts/resolve-core-lib-version.sh

      - name: Download core libs
        run: scripts/download-core-libs.sh
        env:
          CORE_LIB_VERSION: ${{ steps.resolve-version.outputs.core_lib_version }}
          TARGET_PLATFORMS: "macos" # "macos linux windows"
          LIB_EXTENSIONS: ".dylib" # ".dylib .so .dll"

      - name: Upload core libs artifacts
        uses: actions/upload-artifact@v4
        with:
          name: core-libs
          path: core-libs
  
  run-tests:
    needs: fetch-core-libs
    runs-on: macos-14
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download core libs artifacts
        uses: actions/download-artifact@v4
        with:
          name: core-libs
          path: core-libs
        
      - name: Restore core libs
        run: scripts/restore-core-libs.sh

      - name: Setup Swift
        uses: SwiftyLab/setup-swift@latest
        with:
          swift-version: "6.1.0"

      - name: Run tests
        run: swift test
